version: '3.0'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'OFF'
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: "no"
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'OFF'
      KAFKA_LOG4J_LOGGERS: 'kafka=OFF,kafka.controller=OFF,kafka.log.LogCleaner=OFF,state.change.logger=OFF,kafka.producer.async.DefaultEventHandler=OFF'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: "no"
    environment:
      MONGODB_URI: mongodb://mongo:27017/recommendations
    command: mongod --quiet --logpath /dev/null

  travel_rec:
    build: ./components/travel_rec
    ports:
      - '3000:3000'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=recommendations
      - MONGODB_URI=mongodb://mongo:27017/recommendations
      - MONGODB_DATABASE=recommendations
      - START_UP_SLEEP_TIME=10
      - START_UP_RETRIES=3
      - RETRY_SLEEP_TIME=3
    depends_on:
      - kafka
      - mongo

  background_worker:
    build: ./components/background_worker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=recommendations
      - MONGODB_URI=mongodb://mongo:27017/recommendations
      - MONGODB_DATABASE=recommendations
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - START_UP_SLEEP_TIME=10
      - START_UP_RETRIES=3
      - RETRY_SLEEP_TIME=3
    depends_on:
      - kafka
      - mongo

volumes:
  mongo-data: {}